// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Banking_Application.Models
{
    public partial class AdminTable
    {
        public int? Id { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
    }
}