// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Banking_Application.Models
{
    public partial class Debit
    {
        public int? Sno { get; set; }
        public string Date { get; set; }
        public decimal? AccountNo { get; set; }
        public string Name { get; set; }
        public decimal? OldBalance { get; set; }
        public string Mode { get; set; }
        public decimal? DebAmount { get; set; }
    }
}