// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Banking_Application.Models
{
    public partial class Fd
    {
        public int? Sno { get; set; }
        public decimal? AccountNo { get; set; }
        public string Mode { get; set; }
        public string Rupees { get; set; }
        public int? Period { get; set; }
        public decimal? InterestRate { get; set; }
        public string MaturityDate { get; set; }
        public decimal? MaturityAmount { get; set; }
        public string StartDate { get; set; }
    }
}