// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Banking_Application.Models
{
    public partial class UserAccount
    {
        public decimal? AccountNo { get; set; }
        public string Name { get; set; }
        public string Dob { get; set; }
        public string PhoneNo { get; set; }
        public string Address { get; set; }
        public string District { get; set; }
        public string State { get; set; }
        public byte[] Picture { get; set; }
        public string Gender { get; set; }
        public string MaritialStatus { get; set; }
        public string MotherName { get; set; }
        public string FatherName { get; set; }
        public decimal? Balance { get; set; }
        public string Date { get; set; }
    }
}